[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install --assume-yes libfontconfig1-dev:$CROSS_DEB_ARCH"
]

[target.powerpc64le-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install --assume-yes libfontconfig1-dev:$CROSS_DEB_ARCH"
]

[target.aarch64-apple-darwin]
image = "freeznet/aarch64-apple-darwin-cross:11.3.1"

[target.x86_64-apple-darwin]
image = "freeznet/x86_64-apple-darwin-cross:11.3.1"